// Solutions We Build — all five industries, transcribed from the live site.
// icon fields are comma-separated Lucide candidate names (first that exists wins).

const INDUSTRIES = [
  {
    id: "ai",
    tab: "AI Automation",
    tabIcon: "Sparkles",
    accent: "#2563EB", accent2: "#4F46E5",
    title: "AI Workflow Automation",
    desc: "Automate repetitive tasks, connect your tools, and turn data into intelligent actions.",
    leftLabel: "Connect Your Systems",
    // connector-style modules (no description)
    modules: [
      { icon: "Mail", title: "Email" },
      { icon: "Users,Contact", title: "CRM" },
      { icon: "Layers,Database", title: "ERP" },
      { icon: "FileText", title: "Documents" },
      { icon: "Webhook,Code", title: "APIs / Webhooks" },
    ],
    hubIcon: "BrainCircuit,Brain,Cpu",
    hubLabel: "AI PROCESSING LAYER",
    hubTagline: "Understand, analyze, and process data using advanced AI models.",
    rightLabel: "Intelligent Outcomes",
    outcomes: [
      { icon: "Zap", title: "Workflow Automation", desc: "Automate end-to-end business processes." },
      { icon: "CircleCheck,CheckCircle", title: "Smart Recommendations", desc: "AI-driven insights and actionable suggestions." },
      { icon: "RefreshCw,BarChart3", title: "Data Synchronization", desc: "Keep systems and data accurate and up-to-date." },
      { icon: "Bell", title: "Alerts & Notifications", desc: "Real-time alerts for important events and exceptions." },
    ],
    features: [
      { icon: "ShieldCheck,Shield", title: "Secure by Design", desc: "Enterprise-grade security at every layer." },
      { icon: "Boxes,Box", title: "Scalable Architecture", desc: "Built to handle growth and complexity." },
      { icon: "Database", title: "Data-Driven", desc: "Make smarter decisions with real-time data." },
      { icon: "Clock", title: "Faster ROI", desc: "Reduce manual work and operational costs." },
    ],
  },
  {
    id: "logistics",
    tab: "Logistics",
    tabIcon: "Truck",
    accent: "#2563EB", accent2: "#3B82F6",
    title: "Logistics Control Tower",
    desc: "Real-time visibility across inventory, dispatch, and delivery operations. Optimize every step of your supply chain.",
    leftLabel: "Operational Modules",
    modules: [
      { icon: "TrendingUp,BarChart3", title: "Demand Forecasting", desc: "AI-driven demand prediction" },
      { icon: "Package,Box", title: "Inventory Planning", desc: "Smart inventory optimization" },
      { icon: "Warehouse,Building2", title: "Warehouse Operations", desc: "Real-time warehouse visibility" },
      { icon: "Truck", title: "Dispatch Optimization", desc: "Route & load optimization" },
      { icon: "Gauge,LayoutDashboard", title: "Executive Dashboard", desc: "Live KPIs & performance" },
    ],
    hubIcon: "TowerControl,RadioTower,Building2",
    hubLabel: "LOGISTICS CONTROL TOWER",
    hubTagline: "Unified data. Smarter decisions. Faster deliveries.",
    rightLabel: "Business Outcomes",
    outcomes: [
      { icon: "Eye", title: "Real-time Visibility", desc: "End-to-end visibility across the supply chain." },
      { icon: "DollarSign", title: "Cost Optimization", desc: "Reduce inventory holding and operational costs." },
      { icon: "Clock", title: "On-time Deliveries", desc: "Improve delivery performance and customer satisfaction." },
      { icon: "Settings", title: "Operational Efficiency", desc: "Automate workflows and eliminate manual tasks." },
      { icon: "BarChart3,ChartColumn", title: "Data-Driven Decisions", desc: "Actionable insights for smarter planning." },
    ],
    features: [
      { icon: "Network,Workflow", title: "End-to-End Integration", desc: "Seamlessly connects systems across your supply chain." },
      { icon: "Boxes,Box", title: "Scalable Architecture", desc: "Built to scale with your business needs." },
      { icon: "ShieldCheck,Shield", title: "Secure & Reliable", desc: "Enterprise-grade security and 99.9% uptime." },
      { icon: "Sparkles", title: "AI-Powered Insights", desc: "Predict, optimize, and stay ahead of disruptions." },
    ],
  },
  {
    id: "manufacturing",
    tab: "Manufacturing",
    tabIcon: "Factory",
    accent: "#1D4ED8", accent2: "#2563EB",
    title: "Manufacturing Control Tower",
    desc: "Real-time visibility and intelligence across production, quality, assets, and supply chain to maximize output and efficiency.",
    leftLabel: "Operational Modules",
    modules: [
      { icon: "BarChart3,Activity", title: "Production Monitoring", desc: "Track OEE, throughput and downtime" },
      { icon: "ClipboardCheck", title: "Quality Management", desc: "Ensure quality at every stage" },
      { icon: "Wrench", title: "Equipment Maintenance", desc: "Predictive maintenance and asset health" },
      { icon: "Package,Box", title: "Supply Chain Visibility", desc: "Supplier, materials and inventory tracking" },
      { icon: "BarChart3,ChartColumn", title: "Performance Analytics", desc: "KPIs, reporting and continuous improvement" },
    ],
    hubIcon: "Factory",
    hubLabel: "FACTORY INTELLIGENCE",
    hubTagline: "Unified data. Real-time insights. Smarter decisions. Higher output.",
    rightLabel: "Business Outcomes",
    outcomes: [
      { icon: "Eye", title: "End-to-End Visibility", desc: "Real-time visibility across plants and lines." },
      { icon: "TrendingUp", title: "Higher Productivity", desc: "Improve OEE and reduce downtime." },
      { icon: "CircleCheck,CheckCircle", title: "Better Quality", desc: "Reduce defects and ensure consistent quality." },
      { icon: "DollarSign", title: "Cost Optimization", desc: "Lower waste, optimize usage and reduce costs." },
      { icon: "Boxes,Box", title: "Data-Driven Decisions", desc: "AI-powered insights for faster and smarter decisions." },
    ],
    features: [
      { icon: "ShieldCheck,Shield", title: "Secure & Reliable", desc: "Enterprise-grade security and 99.9% uptime." },
      { icon: "Boxes,Box", title: "Scalable Architecture", desc: "Built to scale with your operations." },
      { icon: "Database", title: "Data Integration", desc: "Seamlessly integrate with ERP, MES, PLM and more." },
      { icon: "Sparkles", title: "AI-Powered Insights", desc: "Predict issues and optimize performance." },
    ],
  },
  {
    id: "identity",
    tab: "Identity & Security",
    tabIcon: "ShieldCheck,Shield",
    accent: "#2563EB", accent2: "#1E40AF",
    title: "Identity & Security Systems",
    desc: "Secure identities, protect data, and ensure compliance with intelligent access and zero-trust architectures.",
    leftLabel: "Security Modules",
    modules: [
      { icon: "UserCog,Users", title: "Identity Management", desc: "User lifecycle, provisioning and access control" },
      { icon: "ShieldCheck", title: "Access Governance", desc: "Role-based access and policy enforcement" },
      { icon: "Lock,KeyRound", title: "Authentication", desc: "Multi-factor authentication and single sign-on" },
      { icon: "ShieldAlert,AlertTriangle", title: "Threat Detection", desc: "AI-powered threat monitoring and anomaly detection" },
      { icon: "ClipboardCheck", title: "Compliance & Audit", desc: "Policy compliance, logging and audit trails" },
    ],
    hubIcon: "ShieldCheck,Shield",
    hubLabel: "IDENTITY ENGINE",
    hubTagline: "Unified identity. Zero trust security. Complete protection.",
    rightLabel: "Business Outcomes",
    outcomes: [
      { icon: "ShieldCheck", title: "Stronger Security", desc: "Reduce breaches and protect sensitive data." },
      { icon: "UserCheck,Users", title: "Seamless Access", desc: "Enable secure access across apps and devices." },
      { icon: "FileCheck,ClipboardCheck", title: "Regulatory Compliance", desc: "Meet standards with automated policies and audit logs." },
      { icon: "BarChart3", title: "Lower Risk & Cost", desc: "Minimize security risks and reduce operational overhead." },
      { icon: "ShieldCheck,Shield", title: "User Trust & Confidence", desc: "Build trust with secure and reliable identity experiences." },
    ],
    features: [
      { icon: "ShieldCheck,Shield", title: "Zero Trust Security", desc: "Verify every user and every access request." },
      { icon: "Boxes,Box", title: "Scalable Architecture", desc: "Built to scale across users, systems, and environments." },
      { icon: "Database,Lock", title: "Data Protection", desc: "End-to-end encryption and data privacy by design." },
      { icon: "Sparkles", title: "AI-Powered Insights", desc: "Detect threats, anomalies, and risks in real time." },
    ],
  },
  {
    id: "energy",
    tab: "Energy & Sustainability",
    tabIcon: "Leaf",
    accent: "#10B981", accent2: "#22C55E",
    title: "Energy & Sustainability Intelligence",
    desc: "Monitor, optimize, and future-proof your energy operations while driving sustainability goals and reducing environmental impact.",
    leftLabel: "Operational Modules",
    modules: [
      { icon: "Activity,Gauge", title: "Energy Monitoring", desc: "Real-time tracking of energy usage and performance" },
      { icon: "Zap", title: "Asset Management", desc: "Monitor assets, health and lifecycle" },
      { icon: "PieChart,Clock", title: "Performance Analytics", desc: "AI-driven insights and predictive analytics" },
      { icon: "Leaf", title: "Sustainability Tracking", desc: "Track emissions, water, and waste metrics" },
      { icon: "FileText", title: "Compliance Management", desc: "Ensure regulatory compliance and reporting" },
    ],
    hubIcon: "Leaf",
    hubLabel: "DECISION INTELLIGENCE",
    hubTagline: "Unified data. Smarter insights. Sustainable outcomes.",
    rightLabel: "Business Outcomes",
    outcomes: [
      { icon: "Cloud,CloudOff", title: "Reduce Emissions", desc: "Minimize carbon footprint with data-driven actions." },
      { icon: "DollarSign", title: "Lower Energy Costs", desc: "Optimize consumption and reduce operational costs." },
      { icon: "TrendingUp,Activity", title: "Improve Reliability", desc: "Predict issues and ensure uninterrupted operations." },
      { icon: "ShieldCheck", title: "Regulatory Compliance", desc: "Stay compliant with evolving energy regulations." },
      { icon: "Globe,Leaf", title: "Sustainable Growth", desc: "Build a greener tomorrow while driving business growth." },
    ],
    features: [
      { icon: "ShieldCheck,Shield", title: "Secure & Reliable", desc: "Enterprise-grade security and 99.9% uptime." },
      { icon: "Boxes,Box", title: "Scalable Architecture", desc: "Built to scale across sites, regions, and systems." },
      { icon: "Database", title: "Data Integration", desc: "Seamlessly integrate with IoT, SCADA, ERP and more." },
      { icon: "Sparkles", title: "AI-Powered Insights", desc: "Predict, optimize, and drive smarter decisions." },
    ],
  },
];

window.INDUSTRIES = INDUSTRIES;
